FROM yudhiwidyatama/s2i-php56-pdoocirfc

# This image provides an Apache+PHP environment for running PHP
# applications.

EXPOSE 8080

USER root

# Install Apache httpd and PHP
RUN INSTALL_PKGS="java-1.8.0-openjdk-devel" && \
    yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum clean all -y

USER 1001

# Set the default CMD to print the usage of the language image
CMD $STI_SCRIPTS_PATH/usage
